apiVersion: apps/v1
kind: Deployment
metadata:
  name: externalSvr
  labels:
    app: externalSvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: externalSvr
  template:
    metadata:
      labels:
        app: externalSvr
    spec:
      containers:
        - name: externalSvr
          image: username/externalSvr:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5